apiVersion: v1
kind: Service
metadata:
  name: echo-server
  namespace: my-app
  labels:
    app: echo-server
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: echo-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: my-app
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      serviceAccountName: echo-server
      containers:
      - name: echo
        image: ealen/echo-server:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-server
  namespace: my-app

