apiVersion: v1
kind: Namespace
metadata:
  name: shared-services
  labels:
    name: shared-services
    managed-by: platform-team
  annotations:
    description: "Shared services namespace for databases, message queues, and other shared infrastructure"
