apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-default
  namespace: team-a
  labels:
    tenant: team-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: team-a-app
  namespace: team-a
  labels:
    tenant: team-a
    app: my-app
